version: '3'

services:
  app:
    build: .
    container_name: 'project-google-spreadsheet'
    working_dir: '/root'
    privileged: true
    # restart: always
    tty: true
    volumes:
      - ./opt:/root/opt

